version: "3.9"

services:
  fail2ban:
    image: crazymax/fail2ban:0.11.2
    container_name: fail2ban
    hostname: fail2ban
    restart: unless-stopped
    cap_add:
      - net_admin
      - net_raw
    environment:
      - TZ=Europe/Madrid
      - F2B_LOG_TARGET=/var/log/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=30d
      - TELEGRAM_AUTH_TOKEN=$AUTH_TOKEN
      - TELEGRAM_CHAT_ID=$CHAT_ID
    volumes:
      - ./config:/data
      - ./action.d:/data/action.d:ro
      - ./filter.d:/data/filter.d:ro
      - ./jail.d:/data/jail.d:ro
      - ./scripts:/data/scripts:ro
      - /var/log:/var/log
    network_mode: host

networks:
  default:
    name: traefik
    external: true
