version: "3.9"

services:
  traefik:
    image: traefik:2.10.7
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - DUCKDNS_TOKEN=$DUCKDNS_TOKEN
      - GODADDY_API_SECRET=$GODADDY_SECRET
      - GODADDY_API_KEY=$GODADDY_KEY
    ports:
      - 80:80
      - 443:443
      - 8085:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    extra_hosts:
      - host.docker.internal:172.17.0.1 # https://doc.traefik.io/traefik/providers/docker/#host-networking

  errorpages:
    image: tarampampam/error-pages:latest
    container_name: errorpages
    hostname: errorpages
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TEMPLATE_NAME=connection

networks:
  default:
    name: traefik
    external: true
