---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ./config:/config
      - /path/to/books:/books
    ports:
      - 8083:8083/tcp
      - 8083:8083/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.http.routers.calibre.rule=Host(`calibre.domain.com`)"
      - "traefik.http.routers.calibre.tls.certresolver=letsencrypt"
networks:
  default:
    external: true
    name: traefik
