services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    mem_limit: 8000M
    cpus: 1.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DB_HOSTNAME=192.168.x.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.x.x
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5433 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=1960 #optional
    volumes:
      - ./config:/config
      - ./photos:/photos
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8035:8080
    restart: always
    labels:
      glance.name: Immich
      glance.icon: /assets/immich.svg
      glance.url: http://192.168.x.x:8035
      glance.description: Image & video management
      glance.id: immich
      glance.hide: false

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-immich
    restart: always
    labels:
      glance.parent: immich
      glance.name: Redis
      glance.hide: false

  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5433:5432
    container_name: postgres14-immich
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      glance.parent: immich
      glance.name: Postgres
      glance.hide: false

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    user: 1000:1000
    restart: always
    labels:
      glance.parent: immich
      glance.name: Postgres Backup
      glance.hide: false
    environment:
      POSTGRES_HOST: postgres14
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      SCHEDULE: "0 3 * * *"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 12
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - postgres14

  power-tools:
    container_name: power-tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    environment:
      - IMMICH_API_KEY=redacted
      - IMMICH_URL=http://immich:8080
      - EXTERNAL_IMMICH_URL=https://x.x.es
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres14
      - DB_PORT=5432
      - DB_DATABASE_NAME=immich
    labels:
      glance.parent: immich
      glance.name: PowerTools
      glance.hide: false

networks:
  default:
    external: true
    name: traefik
